#![cfg(test)]

use super::*;

// CPU-instruction harness: measures create_circle / fund / claim, plus a
// synthetic larger-IC Groth16 verify (more public inputs → more g1_mul).
// Tree depth does NOT change claim cost (circuit-only); IC length does.
// Set WRITE_BENCHMARKS=1 to refresh contracts/BENCHMARKS.md.
#[test]
fn cpu_instruction_benchmarks() {
    // ---- create_circle ----
    let env = Env::default();
    env.mock_all_auths();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);
    let admin = Address::generate(&env);
    let token_admin = Address::generate(&env);
    let token = create_token(&env, &token_admin);
    let root = real_root(&env);
    let vk = real_verification_key(&env);
    client.create_circle(&admin, &token, &root, &100i128, &5u32, &0u32, &vk, &0u32, &Address::generate(&env));
    let create_cpu = env.cost_estimate().budget().cpu_instruction_cost();
    std::println!("bench create_circle: {create_cpu} CPU instructions");

    // ---- fund (one member) ----
    let token_admin_client = token::StellarAssetClient::new(&env, &token);
    let member = Address::generate(&env);
    token_admin_client.mint(&member, &100i128);
    client.fund(&0u64, &member);
    let fund_cpu = env.cost_estimate().budget().cpu_instruction_cost();
    std::println!("bench fund:          {fund_cpu} CPU instructions");

    // Fund the remaining 4 so claim can run.
    for _ in 0..4 {
        let m = Address::generate(&env);
        token_admin_client.mint(&m, &100i128);
        client.fund(&0u64, &m);
    }

    // ---- claim (current: 4 public inputs, ic.len() == 5) ----
    let recipient = real_recipient_r0(&env);
    let nullifier_hash = real_nullifier_hash(&env);
    let external_nullifier = real_external_nullifier_round0(&env);
    let proof = real_valid_proof(&env);
    client.claim(
        &0u64,
        &recipient,
        &nullifier_hash,
        &external_nullifier,
        &proof,
    );
    let claim_cpu = env.cost_estimate().budget().cpu_instruction_cost();
    std::println!("bench claim:         {claim_cpu} CPU instructions");

    // Headroom assertion: upgrades that consume the committed safety margin fail loudly.
    assert!(
        claim_cpu < 80_000_000,
        "claim() CPU {claim_cpu} exceeded 80M safety threshold (budget 100M)"
    );

    // ---- larger IC (simulate 5 public inputs → ic.len() == 6) ----
    // Runs the same Groth16 path with one extra g1_mul term (5 instead of
    // 4). Proof will not verify (dummy inputs); we only care about the
    // instruction cost.
    env.cost_estimate().budget().reset_default();
    let mut big_vk = real_verification_key(&env);
    let pad = big_vk.ic.get(0).unwrap();
    big_vk.ic.push_back(pad);
    let zero = Fr::from_u256(U256::from_u32(&env, 0));
    let big_inputs = vec![
        &env,
        nullifier_hash,
        root,
        external_nullifier,
        zero.clone(),
        zero,
    ];
    let _ = Contract::verify_groth16(&env, &big_vk, &proof, &big_inputs);
    let large_ic_cpu = env.cost_estimate().budget().cpu_instruction_cost();
    std::println!("bench verify_groth16 (5 public inputs / ic=6): {large_ic_cpu} CPU instructions");

    if std::env::var_os("WRITE_BENCHMARKS").is_some() {
        const BUDGET: u64 = 100_000_000;
        let headroom = |cost: u64| (BUDGET.saturating_sub(cost) as f64 / BUDGET as f64) * 100.0;
        let table = std::format!(
            "# Contract CPU benchmarks\n\nGenerated by `WRITE_BENCHMARKS=1 cargo test -p sharibo cpu_instruction_benchmarks -- --nocapture`.\n\n| Entrypoint | CPU instructions | Budget headroom |\n| --- | ---: | ---: |\n| `create_circle` | {create_cpu} | {:.1}% |\n| `fund` | {fund_cpu} | {:.1}% |\n| `claim` | {claim_cpu} | {:.1}% |\n| `verify_groth16` (5 public inputs) | {large_ic_cpu} | {:.1}% |\n\nThe `claim` row is gated at 80,000,000 instructions; Stellar's transaction budget is 100,000,000.\n",
            headroom(create_cpu),
            headroom(fund_cpu),
            headroom(claim_cpu),
            headroom(large_ic_cpu),
        );
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../BENCHMARKS.md");
        std::fs::write(path, table).expect("write contracts/BENCHMARKS.md");
    }
}

// ---- Restored (lost in the #235 merge; see PR summary) ----

#[test]
fn claim_fits_cpu_budget() {
    let env = Env::default();
    env.mock_all_auths();
    let s = TestCircle::new(5, 100).build(&env);
    let client = ContractClient::new(&s.env, &s.client_id);
    for m in s.members.iter() {
        client.fund(&s.circle_id, m);
    }
    let recipient = real_recipient_r0(&s.env);
    let nullifier_hash = real_nullifier_hash(&s.env);
    let external_nullifier = real_external_nullifier_round0(&s.env);
    let proof = real_valid_proof(&s.env);
    client.claim(&s.circle_id, &recipient, &nullifier_hash, &external_nullifier, &proof);

    // Cpu limit: 100000000; used: 48066196 (~48%) — comfortably fits.
    // Dominated by Bls12381Pairing (~30.3M) + Bls12381G1Mul (~7.4M, from
    // the two g1_mul calls computing vk_x over 3 public signals) +
    // subgroup checks (~9.3M combined).
    assert!(s.env.cost_estimate().budget().cpu_instruction_cost() < 100_000_000);
}
